In [1]:
import numpy as np

In [4]:
# Creating a numpy array
l=[1,2,3,4,5,6,7]
narray=np.array(l)
print(narray)
print(type(narray))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [5]:
# generating n number of random elemented list
np.random.random(10)

array([0.69456011, 0.7631667 , 0.28323286, 0.84267563, 0.02471747,
       0.47891383, 0.95092682, 0.25330585, 0.49363253, 0.11131043])

In [8]:
# creating Nd array with values from 0 to 1
np.random.rand(1,2)

array([[0.69349592, 0.34480436]])

In [9]:
# creating Nd array with positive and negative values
np.random.randn(1,2)

array([[ 1.15885273, -1.18985087]])

In [10]:
# creating a random integer within a specific range
np.random.randint(1,10)

5

In [12]:
# creating n number of random integers within a specific range
print(np.random.randint(1,1000,10))

[157  81 422 743 940 853 498 477 584 662]


In [14]:
# arange() to arrange the elements with equal distance
np.arange(1,100,10) #note the difference is always 10

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])